# Site settings
title: Minimal Staticman v3 Demo
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://vincenttam.github.io/TestStaticmanLab/"
locale: en
github_username:  VincentTam

# Build settings
markdown: kramdown

staticman:
  api: "https://dev.staticman.net/v3/entry/github/keishakeit/TestStaticmanLab/master/comments"
  path: "_data/comments/test-slug"
